# Generated by Django 5.1.6 on 2025-02-24 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('pcc', models.FileField(upload_to='documents/')),
                ('aadhar', models.FileField(upload_to='documents/')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.tbluserlog')),
            ],
        ),
        migrations.CreateModel(
            name='tblUserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.tbluserlog')),
            ],
        ),
    ]
