# Generated by Django 4.2 on 2025-03-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluserreg',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
