# Generated by Django 4.2 on 2025-04-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexapp", "0002_alter_tbluserreg_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="license",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
