# Generated by Django 4.2 on 2025-04-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexapp", "0003_driver_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="phone_country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
