# Generated by Django 4.2 on 2025-04-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexapp", "0004_driver_country_driver_phone_country_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbluserreg",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tbluserreg",
            name="phone_country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
