# Generated by Django 4.2 on 2025-04-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexapp", "0005_tbluserreg_country_tbluserreg_phone_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="tbluserreg",
            name="phone_number",
            field=models.CharField(max_length=100),
        ),
    ]
