# Generated by Django 5.1.6 on 2025-02-24 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driverApp', '0001_initial'),
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField()),
                ('total_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('driverid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indexapp.driver')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.tbluserreg')),
                ('vehicleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driverApp.vehicle')),
            ],
        ),
    ]
