# Generated by Django 5.1.6 on 2025-02-24 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0001_initial'),
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('regno', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('no_of_seats', models.IntegerField()),
                ('price_per_km', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.category')),
                ('driverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.driver')),
            ],
        ),
    ]
